const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const PORT=process.env.PORT||10000;
const DB=path.join(__dirname,"wheel-data.json"), UP=path.join(__dirname,"uploads");
if(!fs.existsSync(UP))fs.mkdirSync(UP,{recursive:true});
const defaultData={title:"گردونه شانس",description:"جایزه خودت را امتحان کن!",segments:[
{id:1,name:"پیتزا رایگان",description:"یک پیتزای خوشمزه",image:"",chance:25},
{id:2,name:"۲۰٪ تخفیف",description:"۲۰ درصد تخفیف خرید",image:"",chance:25},
{id:3,name:"برگر رایگان",description:"یک برگر رایگان",image:"",chance:25},
{id:4,name:"دوباره تلاش کن",description:"این بار شانس خودت را امتحان کن",image:"",chance:25}]};
function load(){try{return JSON.parse(fs.readFileSync(DB,"utf8"))}catch(e){fs.writeFileSync(DB,JSON.stringify(defaultData,null,2));return defaultData}}
function save(x){fs.writeFileSync(DB,JSON.stringify(x,null,2))}
function json(res,x,status=200){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8"});res.end(JSON.stringify(x))}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function page(){
return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>گردونه شانس</title>
<style>*{box-sizing:border-box}body{margin:0;font-family:Tahoma,Arial;background:linear-gradient(135deg,#fff7ed,#fef2f2);color:#111827}header{background:#111827;color:#fff;text-align:center;padding:22px}main{max-width:1100px;margin:auto;padding:25px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:30px;align-items:center}.wheel{position:relative;text-align:center}canvas{width:min(90vw,520px);height:min(90vw,520px);border-radius:50%;filter:drop-shadow(0 10px 20px #0003)}.pointer{position:absolute;top:-10px;left:50%;transform:translateX(-50%);font-size:42px;z-index:2}button{border:0;border-radius:12px;padding:13px 22px;background:#dc2626;color:#fff;font-size:17px;cursor:pointer}button:disabled{opacity:.5}.card{background:#fff;border-radius:20px;padding:22px;box-shadow:0 8px 30px #0001}.prize{display:flex;gap:12px;align-items:center;padding:12px;border-bottom:1px solid #eee}.prize img,.thumb{width:58px;height:58px;object-fit:cover;border-radius:10px}.result{display:none;margin-top:20px;text-align:center}.result img{max-width:220px;max-height:220px;border-radius:16px}.win{font-size:24px;font-weight:bold;color:#16a34a}@media(max-width:800px){.grid{grid-template-columns:1fr}}
input,textarea{width:100%;padding:10px;border:1px solid #ddd;border-radius:9px;margin:5px 0 12px}label{font-size:14px}.seg{border:1px solid #ddd;border-radius:14px;padding:15px;margin:12px 0}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.admin{max-width:1000px;margin:auto;padding:25px}.ok{color:#15803d}.danger{background:#374151}@media(max-width:700px){.row{grid-template-columns:1fr}}</style></head><body>
<header><h1 id="title">گردونه شانس</h1><div id="desc"></div></header><main><div class="grid"><section class="wheel"><div class="pointer">▼</div><canvas id="c" width="700" height="700"></canvas><br><br><button id="spin">🎡 چرخوندن گردونه</button><div id="result" class="result card"></div></section><section class="card"><h2>🎁 جایزه‌ها</h2><div id="list"></div><p><a href="/admin">⚙️ پنل مدیریت</a></p></section></div></main>
<script>
let D,A=0,busy=false,c=document.getElementById("c"),x=c.getContext("2d");
const safe=s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function draw(){let S=D.segments||[],n=S.length; x.clearRect(0,0,700,700);for(let i=0;i<n;i++){let a=i*2*Math.PI/n+A,b=(i+1)*2*Math.PI/n+A;x.beginPath();x.moveTo(350,350);x.arc(350,350,340,a,b);x.closePath();x.fillStyle=["#f87171","#fbbf24","#34d399","#60a5fa","#a78bfa","#fb7185"][i%6];x.fill();x.strokeStyle="#fff";x.lineWidth=5;x.stroke();let q=(a+b)/2;x.save();x.translate(350+Math.cos(q)*245,350+Math.sin(q)*245);x.rotate(q+Math.PI/2);x.fillStyle="#111827";x.font="bold 21px Tahoma";x.textAlign="center";x.fillText((S[i].name||"جایزه").slice(0,18),0,0);x.restore();if(S[i].image){let im=new Image();im.onload=()=>{x.save();let xx=350+Math.cos(q)*145,yy=350+Math.sin(q)*145;x.beginPath();x.arc(xx,yy,35,0,7);x.clip();x.drawImage(im,xx-35,yy-35,70,70);x.restore()};im.src=S[i].image}}x.beginPath();x.arc(350,350,55,0,7);x.fillStyle="#fff";x.fill();x.strokeStyle="#111827";x.lineWidth=6;x.stroke()}
function render(){title.textContent=D.title;desc.textContent=D.description;list.innerHTML=D.segments.map(s=>'<div class="prize">'+(s.image?'<img src="'+s.image+'">':'<div class="thumb" style="background:#eee"></div>')+'<div><b>'+safe(s.name)+'</b><br><small>'+safe(s.description)+'</small></div></div>').join("");draw()}
function pick(){let t=D.segments.reduce((a,s)=>a+Math.max(0,+s.chance||0),0),r=Math.random()*t;for(let i=0;i<D.segments.length;i++){r-=Math.max(0,+D.segments[i].chance||0);if(r<=0)return i}return D.segments.length-1}
spin.onclick=()=>{if(busy)return;busy=true;spin.disabled=true;let i=pick(),n=D.segments.length,target=-((i+.5)*2*Math.PI/n)+Math.PI/2,start=A,del=target-start;while(del<0)del+=7;del+=Math.PI*12;let t=performance.now();function f(z){let p=Math.min(1,(z-t)/4500),e=1-Math.pow(1-p,3);A=start+del*e;draw();if(p<1)requestAnimationFrame(f);else{let s=D.segments[i];result.style.display="block";result.innerHTML='<div class="win">🎉 تبریک! شما برنده شدید</div><h2>'+safe(s.name)+'</h2><p>'+safe(s.description)+'</p>'+(s.image?'<img src="'+s.image+'">':'');busy=false;spin.disabled=false;result.scrollIntoView({behavior:"smooth"})}}requestAnimationFrame(f)}
fetch("/api/data").then(r=>r.json()).then(z=>{D=z;render()});
</script></body></html>`}
function admin(){
return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>پنل مدیریت</title><style>body{font-family:Tahoma,Arial;background:#f3f4f6;margin:0}.admin{max-width:1000px;margin:auto;padding:25px}.box{background:#fff;padding:22px;border-radius:18px;margin-bottom:20px;box-shadow:0 5px 20px #0001}input,textarea{width:100%;padding:10px;border:1px solid #ddd;border-radius:9px;margin:5px 0 12px}button{background:#111827;color:#fff;border:0;border-radius:10px;padding:11px 17px;cursor:pointer}.seg{border:1px solid #ddd;border-radius:14px;padding:15px;margin:12px 0}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.thumb{width:90px;height:90px;object-fit:cover;border-radius:10px}@media(max-width:700px){.row{grid-template-columns:1fr}}</style></head><body><div class="admin"><h1>⚙️ پنل مدیریت گردونه</h1><div class="box"><h2>اطلاعات سایت</h2><input id="t" placeholder="عنوان"><textarea id="d" placeholder="توضیحات"></textarea><button onclick="settings()">ذخیره</button></div><div class="box"><h2>🎡 تکه‌های گردونه</h2><div id="ss"></div><button onclick="add()">➕ افزودن تکه</button> <button onclick="saveSeg()">💾 ذخیره همه</button> <a href="/">مشاهده سایت</a></div></div>
<script>let D;const E=s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));function render(){t.value=D.title;d.value=D.description;ss.innerHTML=D.segments.map((s,i)=>'<div class="seg"><b>تکه '+(i+1)+'</b><div class="row"><div><label>نام جایزه</label><input data-i="'+i+'" data-k="name" value="'+E(s.name)+'"></div><div><label>شانس برد</label><input type="number" min="0" data-i="'+i+'" data-k="chance" value="'+s.chance+'"></div></div><label>توضیحات</label><textarea data-i="'+i+'" data-k="description">'+E(s.description)+'</textarea><label>عکس این تکه</label><input type="file" accept="image/*" onchange="up(this,'+i+')">'+(s.image?'<br><img class="thumb" src="'+s.image+'">':'')+' <button onclick="del('+i+')">حذف</button></div>').join("")}
function add(){D.segments.push({id:Date.now(),name:"جایزه جدید",description:"",image:"",chance:10});render()}function del(i){if(D.segments.length<2)return alert("حداقل یک تکه لازم است");D.segments.splice(i,1);render()}async function up(el,i){let f=el.files[0];if(!f)return;let fd=new FormData;fd.append("image",f);let r=await fetch("/api/upload",{method:"POST",body:fd}),j=await r.json();if(!r.ok)return alert(j.error||"خطا");D.segments[i].image=j.url;render()}function collect(){document.querySelectorAll("[data-k]").forEach(e=>D.segments[+e.dataset.i][e.dataset.k]=e.dataset.k==="chance"?+e.value:e.value)}async function saveSeg(){collect();let r=await fetch("/api/segments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({segments:D.segments})});D=await r.json();alert("ذخیره شد");render()}async function settings(){let r=await fetch("/api/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:t.value,description:d.value})});D=await r.json();alert("ذخیره شد")}fetch("/api/data").then(r=>r.json()).then(z=>{D=z;render()})</script></body></html>`}
function multipart(buf,boundary){
const parts=buf.toString("binary").split("--"+boundary);let out=null;
for(const p of parts){if(!p.includes("Content-Disposition"))continue;let m=p.match(/name="([^"]+)"/),fn=p.match(/filename="([^"]*)"/);if(!m)continue;let i=p.indexOf("\r\n\r\n");if(i<0)continue;let body=Buffer.from(p.slice(i+4).replace(/\r\n--$/,""),"binary");if(fn&&fn[1])out={name:m[1],filename:fn[1],body};}
return out}
const server=http.createServer((req,res)=>{
if(req.method==="GET"){if(req.url==="/")return res.end(page());if(req.url==="/admin")return res.end(admin());if(req.url==="/api/data")return json(res,load());if(req.url.startsWith("/uploads/")){let f=path.basename(req.url),p=path.join(UP,f);if(fs.existsSync(p)){let ext=path.extname(f).toLowerCase(),types={".jpg":"image/jpeg",".jpeg":"image/jpeg",".png":"image/png",".webp":"image/webp",".gif":"image/gif"};res.writeHead(200,{"Content-Type":types[ext]||"application/octet-stream"});return fs.createReadStream(p).pipe(res)}res.writeHead(404);return res.end("Not found")}return res.writeHead(404),res.end("Not found")}
let chunks=[];req.on("data",c=>chunks.push(c));req.on("end",()=>{let body=Buffer.concat(chunks);
try{
if(req.method==="POST"&&req.url==="/api/settings"){let d=load(),j=JSON.parse(body.toString());d.title=String(j.title||"گردونه شانس");d.description=String(j.description||"");save(d);return json(res,d)}
if(req.method==="POST"&&req.url==="/api/segments"){let d=load(),j=JSON.parse(body.toString());d.segments=(j.segments||[]).map((s,i)=>({id:+s.id||Date.now()+i,name:String(s.name||"جایزه"),description:String(s.description||""),image:String(s.image||""),chance:Math.max(0,+s.chance||0)}));if(!d.segments.length)return json(res,{error:"حداقل یک تکه لازم است"},400);save(d);return json(res,d)}
if(req.method==="POST"&&req.url==="/api/upload"){let ct=req.headers["content-type"]||"",b=ct.match(/boundary=(?:"([^"]+)"|([^;]+))/);if(!b)return json(res,{error:"فرمت آپلود نامعتبر است"},400);let q=multipart(body,b[1]||b[2]);if(!q)return json(res,{error:"عکس پیدا نشد"},400);let ext=path.extname(q.filename).toLowerCase();if(![".jpg",".jpeg",".png",".webp",".gif"].includes(ext))return json(res,{error:"فقط JPG PNG WEBP GIF مجاز است"},400);let fn=crypto.randomBytes(8).toString("hex")+ext;fs.writeFileSync(path.join(UP,fn),q.body);return json(res,{url:"/uploads/"+fn})}
res.writeHead(404);res.end("Not found")
}catch(e){json(res,{error:e.message},500)}})});
server.listen(PORT,"0.0.0.0",()=>console.log("Wheel site running on port "+PORT));
